version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  build:
    desc: Build the Go project
    cmds:
      - go build -o bin/server ./cmd/server
    sources:
      - "**/*.go"
    generates:
      - bin/server

  run:
    desc: Build and run the project
    cmds:
      - task: build
      - ./bin/server

  test:
    desc: Run tests
    cmds:
      - go test ./... -cover

  clean:
    desc: Clean the project
    cmds:
      - rm -rf bin

  lint:
    desc: Run Go linter (golangci-lint)
    cmds:
      - golangci-lint run ./...

  install-deps:
    desc: Install project dependencies
    cmds:
      - go mod tidy
      - go mod download

  format:
    desc: Format Go code using gofmt
    cmds:
      - gofmt -w .

  default:
    desc: Default task (build and run)
    cmds:
      - task: run
