import { ApprovedOperation } from '../types';

export const NOTIFIER_OPERATIONS_CATALOG: ApprovedOperation[] = [
  // ── 1. In-App & Self Notifications (/v1/me/notifications) ──
  {
    id: 'me.notifications.send_inapp',
    domain: 'In-App & Self',
    name: 'Send In-App Notification to Self',
    description: 'Dispatches an in-app notification to the active user identity (/v1/notifications/send)',
    method: 'POST',
    path: '/v1/notifications/send',
    safetyClass: 'LOCAL MUTATION',
    requiresAuth: true,
    defaultBody: {
      type: 'in_app',
      recipient: 'local-admin',
      subject: 'In-App Diagnostic Test Alert',
      content: 'This is a test in-app notification sent from API Test Lab.',
      priority: 'high',
      variables: {
        actionUrl: '/test-center',
      },
    },
  },
  {
    id: 'me.notifications.list',
    domain: 'In-App & Self',
    name: 'List My Notifications',
    description: 'Retrieves all notifications assigned to current user (/v1/me/notifications)',
    method: 'GET',
    path: '/v1/me/notifications',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
    queryParams: [
      { key: 'page', label: 'Page', placeholder: '1' },
      { key: 'pageSize', label: 'Page Size', placeholder: '20' },
      { key: 'channel', label: 'Channel', placeholder: 'in_app' },
    ],
  },
  {
    id: 'me.notifications.unread',
    domain: 'In-App & Self',
    name: 'Get My Unread Notifications',
    description: 'Retrieves unread notifications for current user (/v1/me/notifications/unread)',
    method: 'GET',
    path: '/v1/me/notifications/unread',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
  },
  {
    id: 'me.notifications.unread_count',
    domain: 'In-App & Self',
    name: 'Get My Unread Count',
    description: 'Returns total count of unread notifications (/v1/me/notifications/unread-count)',
    method: 'GET',
    path: '/v1/me/notifications/unread-count',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
  },
  {
    id: 'me.notifications.read_all',
    domain: 'In-App & Self',
    name: 'Mark All My Notifications as Read',
    description: 'Bulk updates status of all unread notifications to read (/v1/me/notifications/read-all)',
    method: 'POST',
    path: '/v1/me/notifications/read-all',
    safetyClass: 'LOCAL MUTATION',
    requiresAuth: true,
  },
  {
    id: 'me.notifications.get_id',
    domain: 'In-App & Self',
    name: 'Get My Notification Detail',
    description: 'Fetches single notification details owned by active user (/v1/me/notifications/:notificationId)',
    method: 'GET',
    path: '/v1/me/notifications/:notificationId',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
    pathParams: [{ key: 'notificationId', label: 'Notification ID', placeholder: 'e.g. uuid-here', required: true }],
  },
  {
    id: 'me.notifications.mark_read',
    domain: 'In-App & Self',
    name: 'Mark Notification as Read',
    description: 'Updates notification read_at timestamp (/v1/me/notifications/:notificationId/read)',
    method: 'PUT',
    path: '/v1/me/notifications/:notificationId/read',
    safetyClass: 'LOCAL MUTATION',
    requiresAuth: true,
    pathParams: [{ key: 'notificationId', label: 'Notification ID', placeholder: 'e.g. uuid-here', required: true }],
  },
  {
    id: 'me.notifications.mark_seen',
    domain: 'In-App & Self',
    name: 'Mark Notification as Seen',
    description: 'Updates notification seen_at timestamp (/v1/me/notifications/:notificationId/seen)',
    method: 'POST',
    path: '/v1/me/notifications/:notificationId/seen',
    safetyClass: 'LOCAL MUTATION',
    requiresAuth: true,
    pathParams: [{ key: 'notificationId', label: 'Notification ID', placeholder: 'e.g. uuid-here', required: true }],
  },
  {
    id: 'me.notifications.mark_click',
    domain: 'In-App & Self',
    name: 'Mark Notification Link Clicked',
    description: 'Updates notification clicked_at timestamp (/v1/me/notifications/:notificationId/click)',
    method: 'POST',
    path: '/v1/me/notifications/:notificationId/click',
    safetyClass: 'LOCAL MUTATION',
    requiresAuth: true,
    pathParams: [{ key: 'notificationId', label: 'Notification ID', placeholder: 'e.g. uuid-here', required: true }],
  },

  // ── 2. Admin Notification Control ──
  {
    id: 'admin.notifications.list_all',
    domain: 'Admin Notifications',
    name: 'List All Notifications (Global)',
    description: 'Admin query across all users and tenants with filters (/v1/admin/notifications)',
    method: 'GET',
    path: '/v1/admin/notifications',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
    queryParams: [
      { key: 'page', label: 'Page', placeholder: '1' },
      { key: 'pageSize', label: 'Page Size', placeholder: '20' },
      { key: 'status', label: 'Status (pending, sent, failed)', placeholder: 'failed' },
      { key: 'channel', label: 'Channel (email, sms, in_app)', placeholder: 'email' },
      { key: 'userId', label: 'User ID', placeholder: 'user-001' },
    ],
  },
  {
    id: 'admin.notifications.get',
    domain: 'Admin Notifications',
    name: 'Get Notification by ID (Admin)',
    description: 'Retrieve single notification with full details (/v1/admin/notifications/:notificationId)',
    method: 'GET',
    path: '/v1/admin/notifications/:notificationId',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
    pathParams: [{ key: 'notificationId', label: 'Notification ID', placeholder: 'e.g. uuid-here', required: true }],
  },
  {
    id: 'admin.notifications.attempts',
    domain: 'Admin Notifications',
    name: 'Get Notification Delivery Attempts',
    description: 'Retrieve individual provider attempt history (/v1/admin/notifications/:notificationId/attempts)',
    method: 'GET',
    path: '/v1/admin/notifications/:notificationId/attempts',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
    pathParams: [{ key: 'notificationId', label: 'Notification ID', placeholder: 'e.g. uuid-here', required: true }],
  },
  {
    id: 'admin.notifications.deliveries',
    domain: 'Admin Notifications',
    name: 'Get Notification Deliveries',
    description: 'Retrieve delivery logs for a notification (/v1/admin/notifications/:notificationId/deliveries)',
    method: 'GET',
    path: '/v1/admin/notifications/:notificationId/deliveries',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
    pathParams: [{ key: 'notificationId', label: 'Notification ID', placeholder: 'e.g. uuid-here', required: true }],
  },
  {
    id: 'admin.notifications.retry',
    domain: 'Admin Notifications',
    name: 'Retry Notification (Admin)',
    description: 'Requeues failed notification for delivery (/v1/admin/notifications/:notificationId/retry)',
    method: 'POST',
    path: '/v1/admin/notifications/:notificationId/retry',
    safetyClass: 'EXTERNAL DELIVERY',
    requiresAuth: true,
    pathParams: [{ key: 'notificationId', label: 'Notification ID', placeholder: 'e.g. uuid-here', required: true }],
  },
  {
    id: 'admin.notifications.cancel',
    domain: 'Admin Notifications',
    name: 'Cancel Notification (Admin)',
    description: 'Cancels pending/queued notification (/v1/admin/notifications/:notificationId/cancel)',
    method: 'POST',
    path: '/v1/admin/notifications/:notificationId/cancel',
    safetyClass: 'LOCAL MUTATION',
    requiresAuth: true,
    pathParams: [{ key: 'notificationId', label: 'Notification ID', placeholder: 'e.g. uuid-here', required: true }],
  },
  {
    id: 'admin.notifications.read_all_user',
    domain: 'Admin Notifications',
    name: 'Mark All Notifications Read for User',
    description: 'Admin bulk mark as read for specific user (/v1/admin/notifications/read-all)',
    method: 'POST',
    path: '/v1/admin/notifications/read-all',
    safetyClass: 'LOCAL MUTATION',
    requiresAuth: true,
    queryParams: [{ key: 'userId', label: 'User ID', placeholder: 'user-001', required: true }],
  },

  // ── 3. Templates & Preview ──
  {
    id: 'templates.list',
    domain: 'Templates & Preview',
    name: 'List Notification Templates',
    description: 'Retrieves all registered notification templates (/v1/templates)',
    method: 'GET',
    path: '/v1/templates',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
  },
  {
    id: 'templates.create',
    domain: 'Templates & Preview',
    name: 'Create Notification Template',
    description: 'Registers a new email/SMS/push template (/v1/templates)',
    method: 'POST',
    path: '/v1/templates',
    safetyClass: 'LOCAL MUTATION',
    requiresAuth: true,
    defaultBody: {
      key: 'welcome_user_v1',
      name: 'Welcome User Email',
      channel: 'email',
      subject: 'Welcome to {{companyName}}, {{userName}}!',
      content: 'Hello {{userName}},\n\nYour account has been created successfully.',
      is_active: true,
      variables: ['userName', 'companyName'],
    },
  },
  {
    id: 'templates.get_by_key',
    domain: 'Templates & Preview',
    name: 'Get Template By Key',
    description: 'Retrieves template definition by key (/v1/templates/key/:key)',
    method: 'GET',
    path: '/v1/templates/key/:key',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
    pathParams: [{ key: 'key', label: 'Template Key', placeholder: 'e.g. welcome_user_v1', required: true }],
  },
  {
    id: 'templates.render_preview',
    domain: 'Templates & Preview',
    name: 'Render Template Preview',
    description: 'Performs dry-run rendering & variable replacement (/v1/templates/render-preview)',
    method: 'POST',
    path: '/v1/templates/render-preview',
    safetyClass: 'SAFE VALIDATION',
    requiresAuth: true,
    defaultBody: {
      key: 'welcome_user_v1',
      variables: {
        userName: 'Alice Smith',
        companyName: 'Acme Corp',
      },
    },
  },

  // ── 4. Providers & Connectivity ──
  {
    id: 'providers.list',
    domain: 'Providers',
    name: 'List Notification Providers',
    description: 'Retrieves configured SMS, Email, and Push providers (/v1/providers)',
    method: 'GET',
    path: '/v1/providers',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
  },
  {
    id: 'providers.create',
    domain: 'Providers',
    name: 'Create Provider',
    description: 'Registers a new provider configuration (/v1/providers)',
    method: 'POST',
    path: '/v1/providers',
    safetyClass: 'LOCAL MUTATION',
    requiresAuth: true,
    defaultBody: {
      name: 'Test SMTP Provider',
      type: 'email',
      provider_key: 'smtp_test_provider',
      is_active: true,
      priority: 10,
      config: {
        host: 'smtp.mailtrap.io',
        port: 2525,
        from_email: 'test@minisource.dev',
      },
    },
  },
  {
    id: 'providers.get',
    domain: 'Providers',
    name: 'Get Provider Details',
    description: 'Fetches provider metadata (/v1/providers/:providerId)',
    method: 'GET',
    path: '/v1/providers/:providerId',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
    pathParams: [{ key: 'providerId', label: 'Provider ID', placeholder: 'e.g. prov-001', required: true }],
  },
  {
    id: 'providers.test',
    domain: 'Providers',
    name: 'Test Provider Connectivity',
    description: 'Validates credentials and connection to provider (/v1/providers/:providerId/test)',
    method: 'POST',
    path: '/v1/providers/:providerId/test',
    safetyClass: 'SAFE VALIDATION',
    requiresAuth: true,
    pathParams: [{ key: 'providerId', label: 'Provider ID', placeholder: 'e.g. prov-001', required: true }],
  },

  // ── 5. Preferences & Reminders ──
  {
    id: 'preferences.get',
    domain: 'Preferences & Reminders',
    name: 'Get My Preferences',
    description: 'Retrieves channel and category preferences for active user (/v1/me/preferences)',
    method: 'GET',
    path: '/v1/me/preferences',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
  },
  {
    id: 'preferences.patch_channel',
    domain: 'Preferences & Reminders',
    name: 'Update Channel Preference',
    description: 'Updates settings for specific channel e.g. email/sms (/v1/me/preferences/channel/:channel)',
    method: 'PATCH',
    path: '/v1/me/preferences/channel/:channel',
    safetyClass: 'LOCAL MUTATION',
    requiresAuth: true,
    pathParams: [{ key: 'channel', label: 'Channel (email, sms, push, in_app)', placeholder: 'email', required: true }],
    defaultBody: {
      is_enabled: true,
      allow_instant: true,
      allow_digest: true,
      digest_frequency: 'daily',
    },
  },
  {
    id: 'reminders.list',
    domain: 'Preferences & Reminders',
    name: 'List My Reminders',
    description: 'Queries scheduled reminders for active user (/v1/me/reminders)',
    method: 'GET',
    path: '/v1/me/reminders',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
  },
  {
    id: 'reminders.create',
    domain: 'Preferences & Reminders',
    name: 'Create My Reminder',
    description: 'Creates a scheduled reminder for active user (/v1/me/reminders)',
    method: 'POST',
    path: '/v1/me/reminders',
    safetyClass: 'LOCAL MUTATION',
    requiresAuth: true,
    defaultBody: {
      type: 'email',
      recipient: 'self@minisource.dev',
      subject: 'Follow-up Reminder',
      body: 'Don\'t forget to complete project task.',
      scheduled_at: new Date(Date.now() + 3600000).toISOString(),
    },
  },

  // ── 6. System & Observability ──
  {
    id: 'health.check',
    domain: 'System & Observability',
    name: 'Backend Health Check',
    description: 'Queries backend health status (/v1/health)',
    method: 'GET',
    path: '/v1/health',
    safetyClass: 'SAFE READ',
    requiresAuth: false,
  },
  {
    id: 'health.readiness',
    domain: 'System & Observability',
    name: 'Readiness Probe',
    description: 'Queries service readiness status (/ready)',
    method: 'GET',
    path: '/ready',
    safetyClass: 'SAFE READ',
    requiresAuth: false,
  },
  {
    id: 'observability.overview',
    domain: 'System & Observability',
    name: 'Observability Health Summary',
    description: 'Retrieves metrics, queue status, and active worker overview (/v1/observability/health)',
    method: 'GET',
    path: '/v1/observability/health',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
  },
  {
    id: 'observability.queue',
    domain: 'System & Observability',
    name: 'Queue Status Overview',
    description: 'Inspects active notification dispatch queues (/v1/observability/queue)',
    method: 'GET',
    path: '/v1/observability/queue',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
  },
  {
    id: 'dashboard.overview',
    domain: 'System & Observability',
    name: 'Dashboard Overview Analytics',
    description: 'Retrieves delivery metrics and volume trends (/v1/dashboard/overview)',
    method: 'GET',
    path: '/v1/dashboard/overview',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
  },
  {
    id: 'settings.get',
    domain: 'System & Observability',
    name: 'Get Global Notification Settings',
    description: 'Queries system settings, quiet hours, and rate limits (/v1/admin/settings/notifications)',
    method: 'GET',
    path: '/v1/admin/settings/notifications',
    safetyClass: 'SAFE READ',
    requiresAuth: true,
  },
];
